name: candidate-recommendation-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22.3
  - pip:
    - mlflow==2.19.0
    - scikit-learn==1.3.2
    - pandas==2.1.4
    - numpy==1.26.2
    - matplotlib==3.8.2
    - seaborn==0.13.0
    - optuna==3.5.0
    - joblib==1.3.2