name: mlops-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - mlflow>=2.0.0
    - scikit-learn>=1.0.0
    - pandas>=1.3.0
    - numpy>=1.21.0
    - flask>=2.0.0
    - fastapi>=0.68.0
    - uvicorn>=0.15.0
    - prometheus_client>=0.14.0
    - joblib>=1.0.0
    - scipy>=1.7.0
    - click>=8.0.0
    - pyyaml>=6.0.0
    - requests>=2.25.0
    - gunicorn>=20.0.0